* Firefox privacy config generator

I found [[https://gist.github.com/0XDE57/fbd302cef7693e62c769][this gist]] that has some very useful Firefox configuration settings around privacy and performance. I thought it'd be neat to automatically transform that into a Javascript snippet that can be dropped into a Firefox profile's `user.js` file. So I built that, in the worst possible way.

It runs in Travis CI when the gist gets updated *FIXME make it run when the gist gets updated* right now it's just daily lol and generates [[tree/master/user.js][this user.js file]]. Copy it into your Firefox profile (appending to your existing user.js, if you have one) to use it. If you don't know where to find your Firefox profile, [[https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data][look here]].

The gist is super cool, but it isn't mine, and I'm not proud of anything I've done here. I hereby license the contents of this repository under the terms of WTFPL, in that document's latest version. Share and Enjoy.
